### PR TITLE
Add experimental python 3 support

### PR DESCRIPTION
**Pull request by superMDguy**
I added a new bazel build rule for python 3 (deepmind_lab_py3.so), and added tests and examples based on the python 2 ones.  I also updated the build docs to describe how to get it working with python 3.  This addresses issues #40 and #33.

### CODE REVIEW

**Comment by joao-alex-cunha** [comment]
I can confirm that cloning this repo allowed me to run deepmind lab random_agent with python3

**Comment by tkoeppe** [comment]
I'll try to take a stab at getting the *same* code to work in Py2 and Py3. That would be a viable outcome.

**Comment by tkoeppe** [comment]
I pushed an update to the native module code via https://github.com/deepmind/lab/commit/b01c3d62b92fdfe6d3bdb26a4c2ec25d803504bd. Feel free to rebase; hopefully this will simplify your approach a little.

**Comment by tkoeppe** [comment]
Have a look at https://github.com/deepmind/lab/commit/3fd858265813bc3475df27a60b2705649b131e2d. I think it should be possible to use Python 2 and 3 now, and with a bit of effort, even on the same Python code.

Check out the Bazel attributes related to choosing a Python version, too: https://docs.bazel.build/versions/master/be/python.html#py_binary_args

**Pull request closed without merging**
