### PR TITLE
Fix exception causes in game_controller.py

### PR DESCRIPTION
**Pull request by cool-RR**
More context for this change here: https://blog.ram.rachum.com/post/621791438475296768/improving-python-exception-chaining-with

### CODE REVIEW

**Comment by cool-RR** [comment]
Looks like the CI failure is not related to my changes.

**Comment by tkoeppe** [comment]
No, we need to update the requirements to at least C++14 first, since Abseil has those requirements too now.

**Comment by cool-RR** [comment]
So this PR can proceed and we can ignore the CI failure?

**Comment by tkoeppe** [comment]
Could you please rebase this PR? The CI should pass then.

**Comment by tkoeppe** [comment]
Hang on, I'm updating the requirements to C++17, then the tests should pass.

**Comment by cool-RR** [comment]
@tkoeppe Would that update come as a commit to the master branch? Because my commit is already rebased on top of the latest commit on master.

**Comment by tkoeppe** [comment]
I'll be in touch. I need to update a few things first, it seems.

**Comment by tkoeppe** [comment]
Can you please rebase and retry now?

**Review by tomwardio — APPROVED** [review]

**Comment by tkoeppe** [comment]
Thank you!

**Pull request merged**
